### ISSUE TITLE
mix compile fails

### ISSUE THREAD

**Issue by kuroda** [oiax/nano_planner#14]
```
14:35:46.988 [info]  Application telemetry exited: :telemetry_app.start(:normal, []) returned an error: shutdown: failed to start child: :telemetry_handler_table
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :telemetry_handler_table.start_link/0 is undefined (module :telemetry_handler_table is not available)
            (telemetry 0.4.3) :telemetry_handler_table.start_link()
            (stdlib 3.14.2.3) supervisor.erl:385: :supervisor.do_start_child_i/3
            (stdlib 3.14.2.3) supervisor.erl:371: :supervisor.do_start_child/2
            (stdlib 3.14.2.3) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 3.14.2.3) supervisor.erl:1171: :supervisor.children_map/4
            (stdlib 3.14.2.3) supervisor.erl:321: :supervisor.init_children/2
            (stdlib 3.14.2.3) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14.2.3) gen_server.erl:385: :gen_server.init_it/6

14:35:47.013 [info]  Application plug_crypto exited: :stopped

14:35:47.013 [info]  Application mime exited: :stopped

14:35:47.013 [info]  Application eex exited: :stopped

could not compile dependency :phoenix_live_dashboard, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix_live_dashboard", update it with "mix deps.update phoenix_live_dashboard" or clean it with "mix deps.clean phoenix_live_dashboard"
** (MatchError) no match of right hand side value: {:error, {:telemetry, {{:shutdown, {:failed_to_start_child, :telemetry_handler_table, {:EXIT, {:undef, [{:telemetry_handler_table, :start_link, [], []}, {:supervisor, :do_start_child_i, 3, [file: 'supervisor.erl', line: 385]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 371]}, {:supervisor, :"-start_children/2-fun-0-", 3, [file: 'supervisor.erl', line: 355]}, {:supervisor, :children_map, 4, [file: 'supervisor.erl', line: 1171]}, {:supervisor, :init_children, 2, [file: 'supervisor.erl', line: 321]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}]}}}}, {:telemetry_app, :start, [:normal, []]}}}}
    (phoenix 1.5.8) lib/mix/tasks/compile.phoenix.ex:11: Mix.Tasks.Compile.Phoenix.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
```

**Comment by kuroda** [comment]
```
$ git clone -b volume03-rev https://github.com/oiax/nano_planner.git np
$ cd np
```
